### ISSUE TITLE
Pager not working in iOS

### ISSUE THREAD

**Issue by johny8228** [triniwiz/nativescript-pager#160]
The pager is no longer working after upgrading to 

nativescript 6.4.0
tns-ios 6.4.0
tns-core-modules 6.4.0

Everything builds fine (I'm using sidekick and cloud builds on windows 10 with ios device) but at runtime I'm getting the following error:

at file:///node_modules\nativescript-angular\platform-common.js:210:0
at file:///node_modules\nativescript-angular\platform-common.js:111:0
at file:///node_modules\nativescript-angular\platform-common.js:91:0
at ./main.ts(file:///app/bundle.js:886:123)
at __webpack_require__(file:///app\webpack\bootstrap:74:0)
at checkDeferredModules(file:///app/runti<\M-b\M^@\M-&>
JavaScript error:
file:///node_modules\nativescript-pager\pager.js:166:0: JS ERROR ReferenceError: Metadata for "CHIPageControl." found but symbol not available

**Comment by johny8228** [comment]
Hi @triniwiz any fix for this planned?

**Comment by triniwiz** [comment]
@johny8228 in next major release, currently in progress.

**Comment by johny8228** [comment]
Thanks!

**Comment by johny8228** [comment]
Still an issue : 

JavaScript stack trace:
file:///node_modules\nativescript-pager\pager.js:170:0
at file:///node_modules\nativescript-pager\pager.js:153:0
at file:///node_modules\@nativescript\core\ui\core\view-base\view-base.js:553:0
at file:///node_modules\@nativescript\core\ui\core\view-base\view-base.js:532:0
at file:///node_modules\@nativescript\core\ui\core\view-base\view-base.js:539:0
at file:///node_modules\@nativescript\core\ui\layouts\layout-base-common.js:125:0
at file:///node_modules\@nativescript\core\ui\core\view\view-common.js:915:0
at file:///node_modules\@nativescript\core\ui\core\view-base\view-base.js:538:0
at file:///node_modules\@nativescript\core\ui\core\view-base\view-base.js:539:0
at file:///node_modules\@nativescript\core\ui\layouts\layout-base-common.js:125:0
at file:///node_modules\@nativescript\core\ui\core\view\view-common.js:915:0
at file:///node_modules\@nativescript\core\ui\core\view-base\view-base.js:538:0
at file:///node_modules\@nativescript\core\ui\core\view-base\view-base.js:539:0
at file:///node_modules\@nativescript\core\ui\content-view\content-view.js:70:0
at file:///node_modules\@nativescript\core\ui\page\page-common.js:126:0
at file:///node_modules\@nativescript\core\ui\core\view\view-common.js:915:0
at file:///node_modules\@nativescript\core\ui\core\view-base\view-base.js:538:0
at file:///node_modules\@nativescript\core\ui\core\view-base\view-base.js:437:0
at file:///node_modules\@nativescript\core\ui\core\view-base\view-base.js:426:0
at file:///node_modules\@nativescript\core\ui\page\page.js:81:0
at UIApplicationMain([native code])
at run(file:///node_modules\@nativescript\core\application\application.js:312:0)
at file:///node_modules\nativescript-angular\platform-common.js:210:0
at file:///node_modules\nativescript-angular\platform-common.js:111:0
at file:///node_modules\nativescript-angular\platform-common.js:91:0
at ./main.ts(file:///app/bundle.js:792:123)
at __webpack_require__(file:///app\webpack\bootstrap:74:0)
at checkDeferredModules(file:///app/runti<\M-b\M^@\M-&>
JavaScript error:
file:///node_modules\nativescript-pager\pager.js:170:0: JS ERROR ReferenceError: Metadata for "CHIPageControl." found but symbol not available at runtime.
*** JavaScript call stack:
(
0   UIApplicationMain@[native code]
1   run@file:///node_modules\@nativescript\core\application\application.js:312:0
2   @file:///node_modules\nativescript-angular\platform-common.js:210:0
3   @file:///node_modules\nativescript-angular\platform-common.js:111:0
4   @file:///node_modules\nativescript-angular\platform-common.js:91:0
5   ./main.ts@file:///app/bundle.js:792:123
6   __webpack_require__@file:///app\webpack\bootstrap:74:0
7   checkDeferredModules@file:///app\webpack\bootstrap:43:0
8   webpackJsonpCallback@file:///app\webpack\bootstrap:30:0
9   anonymous@file:///app/bundle.js:2:61
10  evaluate@[native code]
11  moduleEvaluation@:1:11
12  @:2:1
13  asyncFunctionResume@:1:11
14  @:24:9
15  promiseReactionJob@:1:11
)
*** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: ReferenceError: Metadata for "CHIPageControl." found but symbol not available at runtime.
at
file:///node_modules\nativescript-pager\pager.js:170:0
at file:///node_modules\nativescript-pager\pager.js:153:0
at file:///node_modules\@nativescript\core\ui\core\view-base\view-base.js:553:0
at file:///node_modules\@nativescript\core\ui\core\view-base\view-base.js:532:0
at file:///node_modules\@nativescript\core\ui\core\view-base\view-base.js:539:0
at file:///node_modules\@nativescript\core\ui\layouts\layout-base-common.js:125:0
at file:///node_modules\@nativescript\core\ui\core\view\view-common.js:915:0
at file:///node_modules\@nativescript\core\ui\core\view-base\view-base.js:538:0
at file:///node_modules\@nativescript\core\ui\core\view-base\view-base.js:539:0
at file:///node_modules\@nativescript\core\ui\layouts\layout-base-common.js:125:0
at file:///node_modules\@nativescript\core\ui\core\view\view-common.js:915:0
at file:///node_modules\@nativescript\core\ui\core\view-base\view-base.js:538:0
at file:///node_modules\@nativescript\core\ui\core\view-base\view-base.js:539:0
at file:///node_modules\@nativescript\core\ui\content-view\content-view.js:70:0
at file:///node_modules\@nativescript\core\ui\page\page-common.js:126:0
at file:///node_modules\@nativescript\core\ui\core\view\view-common.js:915:0
at file:///node_modules\@nativescript\core\ui\core\view-base\view-base.js:538:0
at file:///node_modules\@nativescript\core\ui\core\view-base\view-base.js:437:0
at file:///node_modules\@nativescript\core\ui\core\view-base\view-base.js:426:0
at file:///node_modules\@nativescript\core\ui\page\page.js:81:0
at UIApplicationMain([native code])
at run(file:///node_modules\@nativescript\core\application\application.js:312:0)
at file:///node_modules\nativescript-angular\platform-common.js:210:0
at file:///app/vendor.js:1<\M-b\M^@\M-&>
NativeScript caught signal 6.
Native Stack:
1   0x10559fb7c sig_handler(int)
2   0x1bb180884 <redacted>
3   0x1bb1851d8 <redacted>
4   0x1bb0d9844 abort
5   0x1bb2327d4 __cxa_bad_cast
6   0x1bb2329c4 <redacted>
7   0x1bb19a258 <redacted>
8   0x1bb23f304 <redacted>
9   0x1bb23ec58 __cxa_get_exception_ptr
10  0x1bb23ec18 <redacted>
11  0x1bb19a0d0 <redacted>
12  0x105556e48 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
13  0x105590fd8 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
14  0x1060fe7b8 ffi_closure_SYSV_inner
15  0x1061001b4 .Ldo_closure
16  0x1beed0ab8 <redacted>
17  0x1beed1160 <redacted>
18  0x1bee2a6fc <redacted>
19  0x1bee3e640 <redacted>
20  0x1bee3fa34 <redacted>
21  0x1bee22eb8 <redacted>
22  0x1bf97b3d0 <redacted>
23  0x1c1ede7dc <redacted>
24  0x1c1ee4958 <redacted>
25  0x1c1eef578 <redacted>
26  0x1c1e37f1c <redacted>
27  0x1c1e61c08 <redacted>
28  0x1c1e625fc <redacted>
29  0x1bb3efe68 <redacted>
30  0x1bb3ead54 <redacted>
31  0x1bb3eb320 <redacted>
JS Stack:
UIApplicationMain([native code])
at run(file:///node_modules\@nativescript\core\application\application.js:312:0)
at file:///node_modules\nativescript-angular\platform-common.js:210:0
at file:///node_modules\nativescript-angular\platform-common.js:111:0
at file:///node_modules\nativescript-angular\platform-common.js:91:0
at ./main.ts(file:///app/bundle.js:792:123)
at __webpack_require__(file:///app\webpack\bootstrap:74:0)
at checkDeferredModules(file:///app\webpack\bootstrap:43:0)
at webpackJsonpCallback(file:///app\webpack\bootstrap:30:0)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation
at
at asyncFunctionResume
at
at promiseReactionJob

**Comment by triniwiz** [comment]
fixed: https://github.com/triniwiz/nativescript-pager/commit/059650159301e4de92ca4f44beaa9eb07eabeb82 missed a file

**Comment by johny8228** [comment]
Sorry but this is still not working I updated tns-ios to 6.4.2 and nativescript-pager to alpha4 now I get another error.It's a step forward but this is crashing the app:

JS Stack:
file:///node_modules\nativescript-pager\pager.js:242:0
at file:///node_modules\nativescript-pager\pager.js:141:0
at file:///node_modules\@nativescript\core\ui\core\view-base\view-base.js:553:0
at file:///node_modules\@nativescript\core\ui\core\view-base\view-base.js:532:0
at file:///node_modules\@nativescript\core\ui\core\view-base\view-base.js:437:0
at file:///node_modules\@nativescript\core\ui\core\view-base\view-base.js:426:0
at file:///node_modules\@nativescript\core\ui\layouts\layout-base-common.js:49:0
at file:///node_modules\@nativescript\core\ui\layouts\layout-base.js:17:0
at file:///node_modules\nativescript-angular\view-util.js:95:0
at file:///node_modules\nativescript-angular\view-util.js:79:0
at file:///node_modules\nativescript-angular\view-util.js:41:0
at file:///node_modules\nativescript-angular\renderer.js:95:0
at execRenderNodeAction(file:///node_modules\@angular\core\fesm5\core.js:20057:0)
at visitRenderNode(file:///node_modules\@angular\core\fesm5\core.js:20037:0)
at visitSiblingRenderNodes(file:///node_modules\@angular\core\fesm5\core.js:19986:0)
at visitRootRenderNodes(file:///node_modules\@angular\core\fesm5\core.js:19980:0)
at renderAttachEmbeddedView(file:///node_modules\@angular\core\fesm5\core.js:20435:0)
at attachEmbeddedView(file:///node_modules\@angular\core\fesm5\core.js:20346:0)
at file:///node_modules\@angular\core\fesm5\core.js:20627:0
at file:///node_modules\@angular\core\fesm5\core.js:20609:0
at file:///node_modules\@angular\common\fesm5\common.js:4018:0
at set(file:///node_modules\@angular\common\fesm5\common.js:3980:0)
at updateProp(file:///node_modules\@angular\core\fesm5\core.js:21303:0)
at checkAndUpdateDirectiveInline(file:///node_modules\@angular\core\fesm5\core.js:21054:0)
at prodCheck<\M-b\M^@\M-&>

**Comment by triniwiz** [comment]
New build coming soon also can you share your Nativescript Angular package and version you are using

**Comment by johny8228** [comment]
I'm using "nativescript-angular": "~8.2.0" and angular 8.2.0
